# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='hashtags',
            field=models.ManyToManyField(to='main.Hashtags'),
        ),
    ]
