# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_elements_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='category_id',
            new_name='category',
        ),
    ]
