# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models.elements


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160224_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='category',
            field=models.ForeignKey(default=main.models.elements.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
