# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160224_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
