# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160228_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Currency'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
